set -g mouse on
set -g mode-keys vi

bind -n WheelUpPane if -F "#{pane_in_mode}" "send-keys -M" "copy-mode -e"

# Exit copy-mode on any key and return focus to the shell
bind -T copy-mode Any send -X cancel
bind -T copy-mode-vi Any send -X cancel
